"use client"
import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

type Language = "en" | "es" | "fr" | "de" | "hi"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.flights": "Flights",
    "nav.hotels": "Hotels",
    "nav.trains": "Trains",
    "nav.cabs": "Cabs",
    "nav.holidays": "Holidays",
    "nav.offers": "Offers",
    "nav.support": "Support",
    "nav.login": "Login",
    "hero.title": "Explore the World with",
    "hero.subtitle": "Book flights, hotels, trains, and holidays at the best prices. Trusted by millions worldwide.",
    "search.from": "From",
    "search.to": "To",
    "search.departure": "Departure",
    "search.return": "Return",
    "search.travelers": "Travelers",
    "search.button": "Search Flights",
    // Added missing search labels
    "search.oneWay": "One Way",
    "search.roundTrip": "Round Trip",
    "search.multiCity": "Multi-City",
    "search.searching": "Searching…",
    // Recent searches keys used in UI
    "recent.title": "Recent Searches & Deals",
    "recentSearches.title": "Recent Searches & Deals",
    "recentSearches.route": "Route",
    "recentSearches.startingFrom": "Starting From",
    // Footer keys
    "footer.company": "Company",
    "footer.aboutUs": "About Us",
    "footer.careers": "Careers",
    "footer.blog": "Blog",
    "footer.press": "Press",
    "footer.support": "Support",
    "footer.contactUs": "Contact Us",
    "footer.faqs": "FAQs",
    "footer.helpCenter": "Help Center",
    "footer.status": "Status",
    "footer.policies": "Policies",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.cancellation": "Cancellation",
    "footer.refund": "Refund",
    "footer.services": "Services",
    "footer.flights": "Flights",
    "footer.hotels": "Hotels",
    "footer.trains": "Trains",
    "footer.holidays": "Holidays",
    "footer.followUs": "Follow Us",
    "footer.copyright": "© FlyMate — All rights reserved.",
    "results.found": "Flights Found",
    "results.sort": "Sort by",
    "booking.title": "Complete Your Booking",
    "booking.passenger": "Passenger Details",
    "booking.seats": "Seat Selection",
    "booking.addons": "Add-ons",
    "booking.payment": "Payment",
    "booking.previous": "Previous",
    "booking.next": "Next",
    "booking.complete": "Complete Booking",
  },
  es: {
    "nav.flights": "Vuelos",
    "nav.hotels": "Hoteles",
    "nav.trains": "Trenes",
    "nav.cabs": "Taxis",
    "nav.holidays": "Vacaciones",
    "nav.offers": "Ofertas",
    "nav.support": "Soporte",
    "nav.login": "Iniciar sesión",
    "hero.title": "Explora el mundo con",
    "hero.subtitle":
      "Reserva vuelos, hoteles, trenes y vacaciones a los mejores precios. Confiado por millones en todo el mundo.",
    "search.from": "Desde",
    "search.to": "Hacia",
    "search.departure": "Salida",
    "search.return": "Regreso",
    "search.travelers": "Viajeros",
    "search.button": "Buscar Vuelos",
    // nuevos textos
    "search.oneWay": "Solo ida",
    "search.roundTrip": "Ida y vuelta",
    "search.multiCity": "Multidestino",
    "search.searching": "Buscando…",
    "recent.title": "Búsquedas Recientes y Ofertas",
    "recentSearches.title": "Búsquedas Recientes y Ofertas",
    "recentSearches.route": "Ruta",
    "recentSearches.startingFrom": "Desde",
    "offers.title": "Ofertas Exclusivas",
    "offers.viewAll": "Ver Todas las Ofertas",
    "results.found": "Vuelos Encontrados",
    "results.sort": "Ordenar por",
    "booking.title": "Completa tu Reserva",
    "booking.passenger": "Detalles del Pasajero",
    "booking.seats": "Selección de Asientos",
    "booking.addons": "Complementos",
    "booking.payment": "Pago",
    "booking.previous": "Anterior",
    "booking.next": "Siguiente",
    "booking.complete": "Completar Reserva",
    // footer
    "footer.company": "Compañía",
    "footer.aboutUs": "Sobre nosotros",
    "footer.careers": "Carreras",
    "footer.blog": "Blog",
    "footer.press": "Prensa",
    "footer.support": "Soporte",
    "footer.contactUs": "Contáctanos",
    "footer.faqs": "Preguntas frecuentes",
    "footer.helpCenter": "Centro de ayuda",
    "footer.status": "Estado",
    "footer.policies": "Políticas",
    "footer.privacy": "Privacidad",
    "footer.terms": "Términos",
    "footer.cancellation": "Cancelación",
    "footer.refund": "Reembolso",
    "footer.services": "Servicios",
    "footer.flights": "Vuelos",
    "footer.hotels": "Hoteles",
    "footer.trains": "Trenes",
    "footer.holidays": "Vacaciones",
    "footer.followUs": "Síguenos",
    "footer.copyright": "© FlyMate — Todos los derechos reservados.",
  },
  fr: {
    "nav.flights": "Vols",
    "nav.hotels": "Hôtels",
    "nav.trains": "Trains",
    "nav.cabs": "Taxis",
    "nav.holidays": "Vacances",
    "nav.offers": "Offres",
    "nav.support": "Support",
    "nav.login": "Connexion",
    "hero.title": "Explorez le monde avec",
    "hero.subtitle":
      "Réservez des vols, hôtels, trains et vacances aux meilleurs prix. Approuvé par des millions dans le monde.",
    "search.from": "De",
    "search.to": "Vers",
    "search.departure": "Départ",
    "search.return": "Retour",
    "search.travelers": "Voyageurs",
    "search.button": "Rechercher des Vols",
    // nouveaux textes
    "search.oneWay": "Aller simple",
    "search.roundTrip": "Aller-retour",
    "search.multiCity": "Multi‑ville",
    "search.searching": "Recherche…",
    "recent.title": "Recherches Récentes et Offres",
    "recentSearches.title": "Recherches récentes et offres",
    "recentSearches.route": "Itinéraire",
    "recentSearches.startingFrom": "À partir de",
    "offers.title": "Offres Exclusives",
    "offers.viewAll": "Voir Toutes les Offres",
    "results.found": "Vols Trouvés",
    "results.sort": "Trier par",
    "booking.title": "Complétez votre Réservation",
    "booking.passenger": "Détails du Passager",
    "booking.seats": "Sélection des Sièges",
    "booking.addons": "Suppléments",
    "booking.payment": "Paiement",
    "booking.previous": "Précédent",
    "booking.next": "Suivant",
    "booking.complete": "Terminer la Réservation",
    // pied de page
    "footer.company": "Entreprise",
    "footer.aboutUs": "À propos",
    "footer.careers": "Carrières",
    "footer.blog": "Blog",
    "footer.press": "Presse",
    "footer.support": "Support",
    "footer.contactUs": "Contactez‑nous",
    "footer.faqs": "FAQ",
    "footer.helpCenter": "Centre d’aide",
    "footer.status": "Statut",
    "footer.policies": "Politiques",
    "footer.privacy": "Confidentialité",
    "footer.terms": "Conditions",
    "footer.cancellation": "Annulation",
    "footer.refund": "Remboursement",
    "footer.services": "Services",
    "footer.flights": "Vols",
    "footer.hotels": "Hôtels",
    "footer.trains": "Trains",
    "footer.holidays": "Vacances",
    "footer.followUs": "Suivez‑nous",
    "footer.copyright": "© FlyMate — Tous droits réservés.",
  },
  de: {
    "nav.flights": "Flüge",
    "nav.hotels": "Hotels",
    "nav.trains": "Züge",
    "nav.cabs": "Taxis",
    "nav.holidays": "Urlaub",
    "nav.offers": "Angebote",
    "nav.support": "Unterstützung",
    "nav.login": "Anmelden",
    "hero.title": "Erkunden Sie die Welt mit",
    "hero.subtitle":
      "Buchen Sie Flüge, Hotels, Züge und Urlaub zu den besten Preisen. Vertraut von Millionen weltweit.",
    "search.from": "Von",
    "search.to": "Nach",
    "search.departure": "Abflug",
    "search.return": "Rückkehr",
    "search.travelers": "Reisende",
    "search.button": "Flüge Suchen",
    // neue Texte
    "search.oneWay": "Nur Hinflug",
    "search.roundTrip": "Hin- und Rückflug",
    "search.multiCity": "Multi‑Stadt",
    "search.searching": "Suche…",
    "recent.title": "Letzte Suchen und Angebote",
    "recentSearches.title": "Letzte Suchen & Angebote",
    "recentSearches.route": "Route",
    "recentSearches.startingFrom": "Ab",
    "offers.title": "Exklusive Angebote",
    "offers.viewAll": "Alle Angebote Anzeigen",
    "results.found": "Flüge Gefunden",
    "results.sort": "Sortieren nach",
    "booking.title": "Buchen Sie Ihre Reise",
    "booking.passenger": "Passagierdetails",
    "booking.seats": "Sitzplatzwahl",
    "booking.addons": "Zusatzleistungen",
    "booking.payment": "Zahlung",
    "booking.previous": "Zurück",
    "booking.next": "Weiter",
    "booking.complete": "Buchung Abschließen",
    // Fußzeile
    "footer.company": "Unternehmen",
    "footer.aboutUs": "Über uns",
    "footer.careers": "Karriere",
    "footer.blog": "Blog",
    "footer.press": "Presse",
    "footer.support": "Unterstützung",
    "footer.contactUs": "Kontakt",
    "footer.faqs": "FAQ",
    "footer.helpCenter": "Hilfe‑Center",
    "footer.status": "Status",
    "footer.policies": "Richtlinien",
    "footer.privacy": "Datenschutz",
    "footer.terms": "AGB",
    "footer.cancellation": "Stornierung",
    "footer.refund": "Erstattung",
    "footer.services": "Leistungen",
    "footer.flights": "Flüge",
    "footer.hotels": "Hotels",
    "footer.trains": "Züge",
    "footer.holidays": "Urlaub",
    "footer.followUs": "Folge uns",
    "footer.copyright": "© FlyMate — Alle Rechte vorbehalten.",
  },
  hi: {
    "nav.flights": "उड़ानें",
    "nav.hotels": "होटल",
    "nav.trains": "ट्रेनें",
    "nav.cabs": "कैब",
    "nav.holidays": "छुट्टियां",
    "nav.offers": "ऑफर",
    "nav.support": "सहायता",
    "nav.login": "लॉगिन",
    "hero.title": "FlyMate के साथ दुनिया की खोज करें",
    "hero.subtitle": "सर्वोत्तम कीमतों पर उड़ानें, होटल, ट्रेनें और छुट्टियां बुक करें। दुनिया भर में लाखों द्वारा विश्वसनीय।",
    "search.from": "से",
    "search.to": "को",
    "search.departure": "प्रस्थान",
    "search.return": "वापसी",
    "search.travelers": "यात्री",
    "search.button": "उड़ानें खोजें",
    // नयी कुंजियाँ
    "search.oneWay": "एकतरफ़ा",
    "search.roundTrip": "दोतरफ़ा",
    "search.multiCity": "मल्टी‑सिटी",
    "search.searching": "खोज जारी…",
    "recent.title": "हाल की खोजें और डील",
    "recentSearches.title": "हाल की खोजें और डील",
    "recentSearches.route": "मार्ग",
    "recentSearches.startingFrom": "प्रारंभ मूल्य",
    "offers.title": "विशेष ऑफर",
    "offers.viewAll": "सभी ऑफर देखें",
    "results.found": "उड़ानें मिलीं",
    "results.sort": "इसके अनुसार क्रमबद्ध करें",
    "booking.title": "अपनी बुकिंग पूरी करें",
    "booking.passenger": "यात्री विवरण",
    "booking.seats": "सीट चयन",
    "booking.addons": "ऐड-ऑन",
    "booking.payment": "भुगतान",
    "booking.previous": "पिछला",
    "booking.next": "अगला",
    "booking.complete": "बुकिंग पूरी करें",
    // फ़ूटर
    "footer.company": "कंपनी",
    "footer.aboutUs": "हमारे बारे में",
    "footer.careers": "करियर",
    "footer.blog": "ब्लॉग",
    "footer.press": "प्रेस",
    "footer.support": "सहायता",
    "footer.contactUs": "संपर्क करें",
    "footer.faqs": "अक्सर पूछे जाने वाले प्रश्न",
    "footer.helpCenter": "हेल्प सेंटर",
    "footer.status": "स्थिति",
    "footer.policies": "नीतियाँ",
    "footer.privacy": "गोपनीयता",
    "footer.terms": "नियम व शर्तें",
    "footer.cancellation": "रद्दीकरण",
    "footer.refund": "रिफंड",
    "footer.services": "सेवाएं",
    "footer.flights": "उड़ानें",
    "footer.hotels": "होटल",
    "footer.trains": "ट्रेनें",
    "footer.holidays": "छुट्टियां",
    "footer.followUs": "हमें फ़ॉलो करें",
    "footer.copyright": "© FlyMate — सर्वाधिकार सुरक्षित.",
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")
  const [isClient, setIsClient] = useState(false)

  useEffect(() => {
    setIsClient(true)
    const savedLanguage = localStorage.getItem("language") as Language | null
    if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || translations["en"][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
